services:
  # Backend Service
  - type: web
    name: felicity-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://festAdmin:admin123@festcluster.b75rdes.mongodb.net/fest_management?appName=FestCluster
      - key: JWT_SECRET
        value: evP8PLzg6C8kcU0dT9st8+qk9NKdk7MdS5acezSIZZQ=
      - key: CLIENT_URL
        value: https://felicity-olive.vercel.app
      - key: ADMIN_EMAIL
        value: admin@iiit.ac.in
      - key: ADMIN_PASSWORD
        sync: false
        value: admin123
